name: CD Pipeline

on:
  push:
    branches:
      - test
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }} || ${{ github.event_name == 'push' }}

    steps:
      - name: Trigger Log
        run: echo "Workflow triggered by: ${{ github.event_name }} on branch ${{ github.ref }}"

      - name: Workflow Conclusion Log
        run: echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"

      - name: Deploy to Render
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://api.render.com/v1/deploy/${{ secrets.RENDER_SERVICE_ID }} \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId":"${{ secrets.RENDER_SERVICE_ID }}"}')

          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with response code $response"
            exit 1
          fi
          echo "Deployment was successful!"
