name: CI Pipeline

on:
  push:
    branches:
      - test
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Set environment variable
      run: echo "ENVIRONMENT=test" >> $GITHUB_ENV

  validate:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install --upgrade -r src/requirements.txt

    - name: Run flake8 (Linting)
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run pytest with coverage
      run: pytest --cov=src src/tests/ci --cov-report=html:src/tests/ci/coverage.html

    - name: Run Bandit (Security Check)
      run: bandit -r .
