name: Setup Pipeline

on:
  push:
    branches:
      - develop
      - test

  pull_request:
    branches:
      - develop
      - test

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Set environment variable
      run: echo "ENVIRONMENT=test" >> $GITHUB_ENV
